[tool.poetry]
name = "twitchio"
version = "3.0.0"
description = "An asynchronous Python IRC and API wrapper for Twitch."
authors = ["TwitchIO"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/TwitchIO/TwitchIO"
documentation = "https://twitchio.dev/"
homepage = "https://github.com/TwitchIO/TwitchIO"

include = ["LICENSE"]

keywords = ['twitch', 'bot', 'chat bot', 'async', 'api']
classifiers= [
    "Framework :: AsyncIO",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    ]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "3.8.1"
yt-dlp = "*"
pyaudio = [
    { path = "./._audio_wheels/PyAudio-0.2.11-cp310-cp310-win_amd64.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp310-cp310-win32.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp39-cp39-win_amd64.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp39-cp39-win32.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp38-cp38-win_amd64.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp38-cp38-win32.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp37-cp37m-win_amd64.whl", platform = "windows"},
    { path = "./._audio_wheels/PyAudio-0.2.11-cp37-cp37m-win32.whl", platform = "windows"},
    {version = "0.2.11", platform = "linux" }
]

[tool.poetry.dev-dependencies]
sphinx = { version = "*"}
docutils = { version = "<0.18"}
sphinxcontrib-napoleon = { version = "*"}
sphinxcontrib-asyncio = { version = "*"}
sphinxcontrib-websupport = { version = "*"}
Pygments = { version = "*"}
furo = { version = "*"}
black = "*"
isort = "*"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120

[tool.pyright]
include = [
    "twitchio",
    "twitchio/ext/commands",
    "twitchio/ext/eventsub",
#    "twitchio/ext/pubsub",
    "twitchio/ext/routines",
    "twitchio/ext/sounds"
]
exclude = [
    "**/__pycache__",
    "build",
    "dist",
    "docs",
]
reportMissingImports = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.11"
typeCheckingMode = "basic"

[tool.poetry.extras]
docs = [
    'sphinx',
    'docutils',
    'sphinxcontrib-napoleon',
    'sphinxcontrib-asyncio',
    'sphinxcontrib-websupport',
    'Pygments',
    'furo',
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
